### PR TITLE
Support for 'config get cluster'

### PR DESCRIPTION
**Pull request by kcarlson**
Support for aws auto discovery

### CODE REVIEW

**Comment by ronkorving** [comment]
Can you explain what this does and how, because I'm lost...

**Comment by kcarlson** [comment]
Hi!

Sorry, bad description.

This adds support for the `config get cluster` command particular to AWS's memcached implementation.

See: http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/AutoDiscovery.AddingToYourClientLibrary.html

**Comment by siimon** [comment]
Is it possible to get this merged? We're having the same issue and this fork fixes it

**Comment by CaptainJiNX** [comment]
This would be useful for us, as we are using this for accessing AWS ElastiCache.

**Comment by ronkorving** [comment]
Could you add this information to the code comment to it's at least traceable and maintainable? Thanks :)

**Comment by kcarlson** [comment]
@ronkorving I commented the changes I made.

**Comment by ronkorving** [comment]
@kcarlson thanks!
@siimon @CaptainJiNX this works for you guys?

**Comment by siimon** [comment]
Yes! We're running the fork in production against a memcached elasticache cluster and it works fine!

**Comment by kcarlson** [comment]
@ronkorving Awesome, thanks! How does this get into the npm registery?

**Comment by ronkorving** [comment]
By publishing it :) Enjoy your v2.2.2 release :)

**Comment by shakefu** [comment]
Any chance there's any docs or examples on how to use elasticache autodiscovery?

**Comment by CaptainJiNX** [comment]
I created a small gist with a simplified example of how we are using it:
https://gist.github.com/CaptainJiNX/8137987a7d67a5a55a0168e205d7fd3c

**Pull request merged**
